### ISSUE TITLE
18.4.0-XE is not usable without the password

### ISSUE THREAD

**Issue by bigos** [oracle/vagrant-projects#292]
**Describe the issue**

There is no information about the password displayed when installing the VM.
When I run `vagrant ssh` and the try `sudo su -oracle`, I can change to the oracle user but the password changing script can not be found in ~/oracle directory.

**Environment (please complete the following information):**

- Host OS: Ubuntu 20.04

**Additional information**

None

**Comment by bigos** [comment]
installation stops at:
```
    oracle18c-xe-vagrant: Complete!
    oracle18c-xe-vagrant: INSTALLER: Oracle preinstall and openssl complete
    oracle18c-xe-vagrant: INSTALLER: Environment variables set
```
At this point, the VM is running. Trying to login as oracle with the password specified in Vagrantfile did not work.

```
  # Provision everything on the first run
  config.vm.provision "shell", path: "scripts/install.sh", env:
    {
       "SYSTEM_TIMEZONE"     => VM_SYSTEM_TIMEZONE,
       "ORACLE_CHARACTERSET" => VM_ORACLE_CHARACTERSET,
       "LISTENER_PORT"       => VM_LISTENER_PORT,
       "EM_EXPRESS_PORT"     => VM_EM_EXPRESS_PORT,
       "ORACLE_PWD"          => "oracle"
    }
```

**Comment by bigos** [comment]
Observing the terminal I saw more output after a long while. So I was trying to use incomplete installation. Where in the documentation does it say what should be the end of the output after successfully running `vagrant up` for the first time?

**Comment by bigos** [comment]
The installation is still running, but I have passed the point where it says:
```
    oracle18c-xe-vagrant: Configuring Oracle Database XE.
    oracle18c-xe-vagrant: Enter SYS user password: 
    oracle18c-xe-vagrant: ******
    oracle18c-xe-vagrant: 
    oracle18c-xe-vagrant: *
    oracle18c-xe-vagrant: Enter SYSTEM user password: 
    oracle18c-xe-vagrant: ******
    oracle18c-xe-vagrant: 
    oracle18c-xe-vagrant: ***
    oracle18c-xe-vagrant: Enter PDBADMIN User Password: 
    oracle18c-xe-vagrant: ******
    oracle18c-xe-vagrant: 
    oracle18c-xe-vagrant: *
    oracle18c-xe-vagrant: Prepare for db operation
    oracle18c-xe-vagrant: 7% complete
```

I was able to use SQL developer to login as **system** using my password specified in the Vagrant file.

So I guess the documentation should be more clear about the installation process, so people do not get confused when the installation script says **Complete**!
